//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArabTradersGroup.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ATG {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ATG() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArabTradersGroup.App_LocalResources.ATG", typeof(ATG).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about us.
        /// </summary>
        public static string aboutaboutus {
            get {
                return ResourceManager.GetString("aboutaboutus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Arab Traders Group.
        /// </summary>
        public static string aboutcompany {
            get {
                return ResourceManager.GetString("aboutcompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to how we do.
        /// </summary>
        public static string abouthowwedo {
            get {
                return ResourceManager.GetString("abouthowwedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string aboutus {
            get {
                return ResourceManager.GetString("aboutus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arab Traders Group.
        /// </summary>
        public static string aboutusauthor {
            get {
                return ResourceManager.GetString("aboutusauthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        public static string aboutustab1 {
            get {
                return ResourceManager.GetString("aboutustab1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arab Traders Trading Co. SAE is specialized in marketing and manufacturing legumes, grains, rice and all agricultural crops for import and export. The company is distinguished by its location in the middle of the delta. The company&apos;s factories and mills are characterized by the latest equipment and modern machines. With a storage area of at least 5,000 to 10,000 tons per class and silos equipped for casting, whether from wheat, rice, barley, and broad rice. There are also stations for the sorting and packin [rest of string was truncated]&quot;;.
        /// </summary>
        public static string aboutustab1paragraph {
            get {
                return ResourceManager.GetString("aboutustab1paragraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who We Are.
        /// </summary>
        public static string aboutustab2 {
            get {
                return ResourceManager.GetString("aboutustab2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Arab Traders Company works to modernize the latest modern purification methods and add all new ones in the fields of the company to satisfy and win the confidence of its customers and maintain permanent and continuous markets both internal and external. The company deals both for import and export to more than 46 countries and its geographical and economic location which is easy to reach land and sea easily and the location of its ports and free zones It has been aggressively competing in the European,  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string aboutustab2paragraph {
            get {
                return ResourceManager.GetString("aboutustab2paragraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ho We Do.
        /// </summary>
        public static string aboutustab3 {
            get {
                return ResourceManager.GetString("aboutustab3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We strive to be always in the Arab Republic of Egypt in all our products to always strive for what is best and to create a thought and impression of the company to hold it at home and abroad and to achieve the principles of efficiency, organization, quality and discipline to be always worthy of the trust of our customers and markets around us and our contribution always to serve the consumer and satisfaction and vision and message Arab traders for trading is the development of strategies to be followed, whi [rest of string was truncated]&quot;;.
        /// </summary>
        public static string aboutustab3paragraph {
            get {
                return ResourceManager.GetString("aboutustab3paragraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to who we are.
        /// </summary>
        public static string aboutwhoweare {
            get {
                return ResourceManager.GetString("aboutwhoweare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Employee.
        /// </summary>
        public static string addteam {
            get {
                return ResourceManager.GetString("addteam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD TO CART.
        /// </summary>
        public static string addtocart {
            get {
                return ResourceManager.GetString("addtocart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I agree to the terms.
        /// </summary>
        public static string agreeterms {
            get {
                return ResourceManager.GetString("agreeterms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have an account?.
        /// </summary>
        public static string alreadyhaveaccount {
            get {
                return ResourceManager.GetString("alreadyhaveaccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APPLET Software.
        /// </summary>
        public static string applet {
            get {
                return ResourceManager.GetString("applet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arab Traders Group.
        /// </summary>
        public static string arabtradersgroup {
            get {
                return ResourceManager.GetString("arabtradersgroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Home.
        /// </summary>
        public static string backhome {
            get {
                return ResourceManager.GetString("backhome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string btnaddproduct {
            get {
                return ResourceManager.GetString("btnaddproduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string btneditabout {
            get {
                return ResourceManager.GetString("btneditabout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string btnsaveproduct {
            get {
                return ResourceManager.GetString("btnsaveproduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        public static string btnsignup {
            get {
                return ResourceManager.GetString("btnsignup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View More.
        /// </summary>
        public static string btnviewmore {
            get {
                return ResourceManager.GetString("btnviewmore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string changelanguage {
            get {
                return ResourceManager.GetString("changelanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string company {
            get {
                return ResourceManager.GetString("company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arab Traders Group Products.
        /// </summary>
        public static string companyproducts {
            get {
                return ResourceManager.GetString("companyproducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Team.
        /// </summary>
        public static string companyteam {
            get {
                return ResourceManager.GetString("companyteam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string contact {
            get {
                return ResourceManager.GetString("contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string contactus {
            get {
                return ResourceManager.GetString("contactus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave a messsge here.
        /// </summary>
        public static string contactusleavemessage {
            get {
                return ResourceManager.GetString("contactusleavemessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Right Reserved to.
        /// </summary>
        public static string copyright {
            get {
                return ResourceManager.GetString("copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string country {
            get {
                return ResourceManager.GetString("country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Content/cssadmin/bootstrap.min-en.css.
        /// </summary>
        public static string cssbootstrap {
            get {
                return ResourceManager.GetString("cssbootstrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string cssbootstrapRTL {
            get {
                return ResourceManager.GetString("cssbootstrapRTL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Content/css/bootstrap-en.css.
        /// </summary>
        public static string cssbootstrapu {
            get {
                return ResourceManager.GetString("cssbootstrapu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Content/cssadmin/contacts-en.css.
        /// </summary>
        public static string csscontact {
            get {
                return ResourceManager.GetString("csscontact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Content/cssadmin/details-en.css.
        /// </summary>
        public static string cssdetails {
            get {
                return ResourceManager.GetString("cssdetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Content/cssadmin/faq-en.css.
        /// </summary>
        public static string cssfaq {
            get {
                return ResourceManager.GetString("cssfaq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Content/css/flaticon-en.css.
        /// </summary>
        public static string cssflaticonu {
            get {
                return ResourceManager.GetString("cssflaticonu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://fonts.googleapis.com/css?family=Droid+Sans:400,700.
        /// </summary>
        public static string cssfont {
            get {
                return ResourceManager.GetString("cssfont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Content/cssadmin/font-awesome.min-en.css.
        /// </summary>
        public static string cssfontawesome {
            get {
                return ResourceManager.GetString("cssfontawesome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://fonts.googleapis.com/earlyaccess/droidarabickufi.css.
        /// </summary>
        public static string cssfontu {
            get {
                return ResourceManager.GetString("cssfontu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Content/cssadmin/gallery-en.css.
        /// </summary>
        public static string cssgallery {
            get {
                return ResourceManager.GetString("cssgallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Content/cssadmin/hover-min-en.css.
        /// </summary>
        public static string csshover {
            get {
                return ResourceManager.GetString("csshover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Content/cssadmin/manger-en.css.
        /// </summary>
        public static string cssmanager {
            get {
                return ResourceManager.GetString("cssmanager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Content/cssadmin/media-en.css.
        /// </summary>
        public static string cssmedia {
            get {
                return ResourceManager.GetString("cssmedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Content/cssadmin/media2-en.css.
        /// </summary>
        public static string cssmedia2 {
            get {
                return ResourceManager.GetString("cssmedia2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Content/cssadmin/product-en.css.
        /// </summary>
        public static string cssproduct {
            get {
                return ResourceManager.GetString("cssproduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Content/css/responsive-en.css.
        /// </summary>
        public static string cssresponsiveu {
            get {
                return ResourceManager.GetString("cssresponsiveu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Content/css/revolution-slider-en.css.
        /// </summary>
        public static string cssrevolutionu {
            get {
                return ResourceManager.GetString("cssrevolutionu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Content/cssadmin/singUp-en.css.
        /// </summary>
        public static string csssignup {
            get {
                return ResourceManager.GetString("csssignup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://fonts.googleapis.com/css?family=Droid+Sans:400,700.
        /// </summary>
        public static string csssignupfonts {
            get {
                return ResourceManager.GetString("csssignupfonts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Content/cssadmin/style-en.css.
        /// </summary>
        public static string cssstyle {
            get {
                return ResourceManager.GetString("cssstyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Content/css/style-en.css.
        /// </summary>
        public static string cssstyleu {
            get {
                return ResourceManager.GetString("cssstyleu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Content/cssadmin/team-en.css.
        /// </summary>
        public static string cssteam {
            get {
                return ResourceManager.GetString("cssteam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string dashboard {
            get {
                return ResourceManager.GetString("dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mansoura -Egypt.
        /// </summary>
        public static string dashboardlocation {
            get {
                return ResourceManager.GetString("dashboardlocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current local time in.
        /// </summary>
        public static string dashboardtime {
            get {
                return ResourceManager.GetString("dashboardtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mansoura WEATHER.
        /// </summary>
        public static string dashboardweather {
            get {
                return ResourceManager.GetString("dashboardweather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string date {
            get {
                return ResourceManager.GetString("date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DateTime.
        /// </summary>
        public static string DateTimeModel {
            get {
                return ResourceManager.GetString("DateTimeModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string DescriptionModel {
            get {
                return ResourceManager.GetString("DescriptionModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string EmployeeCountryModel {
            get {
                return ResourceManager.GetString("EmployeeCountryModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DateTime.
        /// </summary>
        public static string EmployeeDateTimeModel {
            get {
                return ResourceManager.GetString("EmployeeDateTimeModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string EmployeeEmailModel {
            get {
                return ResourceManager.GetString("EmployeeEmailModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string EmployeeEmpErrorModel {
            get {
                return ResourceManager.GetString("EmployeeEmpErrorModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string EmployeeFirstNameModel {
            get {
                return ResourceManager.GetString("EmployeeFirstNameModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Id.
        /// </summary>
        public static string EmployeeIdModel {
            get {
                return ResourceManager.GetString("EmployeeIdModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string EmployeeLastNameModel {
            get {
                return ResourceManager.GetString("EmployeeLastNameModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string EmployeePhoneNumberModel {
            get {
                return ResourceManager.GetString("EmployeePhoneNumberModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher.
        /// </summary>
        public static string EmployeePublisherModel {
            get {
                return ResourceManager.GetString("EmployeePublisherModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faq.
        /// </summary>
        public static string faq {
            get {
                return ResourceManager.GetString("faq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string faqadd {
            get {
                return ResourceManager.GetString("faqadd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer.
        /// </summary>
        public static string faqanswer {
            get {
                return ResourceManager.GetString("faqanswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faq Answer Arabic.
        /// </summary>
        public static string FaqAnswerArModel {
            get {
                return ResourceManager.GetString("FaqAnswerArModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faq Answer English.
        /// </summary>
        public static string FaqAnswerEnModel {
            get {
                return ResourceManager.GetString("FaqAnswerEnModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faq DateTime.
        /// </summary>
        public static string FaqDateTimeModel {
            get {
                return ResourceManager.GetString("FaqDateTimeModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string faqdelete {
            get {
                return ResourceManager.GetString("faqdelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string faqedit {
            get {
                return ResourceManager.GetString("faqedit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faq Error.
        /// </summary>
        public static string FaqErrorModel {
            get {
                return ResourceManager.GetString("FaqErrorModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faq Id.
        /// </summary>
        public static string FaqIdModel {
            get {
                return ResourceManager.GetString("FaqIdModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher.
        /// </summary>
        public static string faqpublisher {
            get {
                return ResourceManager.GetString("faqpublisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faq Publisher.
        /// </summary>
        public static string FaqPublisherModel {
            get {
                return ResourceManager.GetString("FaqPublisherModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string faqquestion {
            get {
                return ResourceManager.GetString("faqquestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faq Question Arabic.
        /// </summary>
        public static string FaqQuestionArModel {
            get {
                return ResourceManager.GetString("FaqQuestionArModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faq Question English.
        /// </summary>
        public static string FaqQuestionEnModel {
            get {
                return ResourceManager.GetString("FaqQuestionEnModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faqs.
        /// </summary>
        public static string faqs {
            get {
                return ResourceManager.GetString("faqs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstNameModel {
            get {
                return ResourceManager.GetString("FirstNameModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow Us On.
        /// </summary>
        public static string followus {
            get {
                return ResourceManager.GetString("followus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string footeraddress {
            get {
                return ResourceManager.GetString("footeraddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bashbish, Al Mahalah Al Kubra, Gharbia Governorate.
        /// </summary>
        public static string footeraddressdata {
            get {
                return ResourceManager.GetString("footeraddressdata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designed &amp; Developed By APPLET Software.
        /// </summary>
        public static string footerappletsoftware {
            get {
                return ResourceManager.GetString("footerappletsoftware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyrights © Arab Traders Group 2018. All rights reserved..
        /// </summary>
        public static string footercopyright {
            get {
                return ResourceManager.GetString("footercopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string footeremail {
            get {
                return ResourceManager.GetString("footeremail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to info@arabtradersgroup.com.
        /// </summary>
        public static string footeremailedata {
            get {
                return ResourceManager.GetString("footeremailedata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        public static string footerfax {
            get {
                return ResourceManager.GetString("footerfax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +20402026007.
        /// </summary>
        public static string footerfaxedata {
            get {
                return ResourceManager.GetString("footerfaxedata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Featured links.
        /// </summary>
        public static string footerlinks {
            get {
                return ResourceManager.GetString("footerlinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string footerphone {
            get {
                return ResourceManager.GetString("footerphone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +20402026005
        ///+20402016006
        ///+20402026008.
        /// </summary>
        public static string footerphonedata {
            get {
                return ResourceManager.GetString("footerphonedata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery.
        /// </summary>
        public static string gallery {
            get {
                return ResourceManager.GetString("gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string galleryadd {
            get {
                return ResourceManager.GetString("galleryadd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caption.
        /// </summary>
        public static string gallerycaption {
            get {
                return ResourceManager.GetString("gallerycaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string gallerydelete {
            get {
                return ResourceManager.GetString("gallerydelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string galleryedit {
            get {
                return ResourceManager.GetString("galleryedit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string galleryimage {
            get {
                return ResourceManager.GetString("galleryimage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallary Information.
        /// </summary>
        public static string galleryinformation {
            get {
                return ResourceManager.GetString("galleryinformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string home {
            get {
                return ResourceManager.GetString("home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string ImageModel {
            get {
                return ResourceManager.GetString("ImageModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JobTitle.
        /// </summary>
        public static string JobTitleModel {
            get {
                return ResourceManager.GetString("JobTitleModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KEEP IN TOUCH.
        /// </summary>
        public static string keepintouch {
            get {
                return ResourceManager.GetString("keepintouch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastNameModel {
            get {
                return ResourceManager.GetString("LastNameModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arab Traders Group Gallery.
        /// </summary>
        public static string latestgalleries {
            get {
                return ResourceManager.GetString("latestgalleries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest Products.
        /// </summary>
        public static string latestproducts {
            get {
                return ResourceManager.GetString("latestproducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest Gallery.
        /// </summary>
        public static string lgalleries {
            get {
                return ResourceManager.GetString("lgalleries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string loginu {
            get {
                return ResourceManager.GetString("loginu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Off.
        /// </summary>
        public static string logoff {
            get {
                return ResourceManager.GetString("logoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest Vendors.
        /// </summary>
        public static string lvendors {
            get {
                return ResourceManager.GetString("lvendors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest Vendors.
        /// </summary>
        public static string lvendorsdata {
            get {
                return ResourceManager.GetString("lvendorsdata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager.
        /// </summary>
        public static string manager {
            get {
                return ResourceManager.GetString("manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string manageradd {
            get {
                return ResourceManager.GetString("manageradd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string managerdelete {
            get {
                return ResourceManager.GetString("managerdelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string managerdescription {
            get {
                return ResourceManager.GetString("managerdescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string manageredit {
            get {
                return ResourceManager.GetString("manageredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ManagerErrorModel {
            get {
                return ResourceManager.GetString("ManagerErrorModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string managerfname {
            get {
                return ResourceManager.GetString("managerfname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager Id.
        /// </summary>
        public static string ManagerIdModel {
            get {
                return ResourceManager.GetString("ManagerIdModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string managerimage {
            get {
                return ResourceManager.GetString("managerimage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string managerlname {
            get {
                return ResourceManager.GetString("managerlname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string managerposition {
            get {
                return ResourceManager.GetString("managerposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Managers.
        /// </summary>
        public static string managers {
            get {
                return ResourceManager.GetString("managers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Managers.
        /// </summary>
        public static string managersdata {
            get {
                return ResourceManager.GetString("managersdata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Managers.
        /// </summary>
        public static string managerslatest {
            get {
                return ResourceManager.GetString("managerslatest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string message {
            get {
                return ResourceManager.GetString("message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Faq.
        /// </summary>
        public static string newfaq {
            get {
                return ResourceManager.GetString("newfaq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Manager.
        /// </summary>
        public static string newmanager {
            get {
                return ResourceManager.GetString("newmanager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string newopen {
            get {
                return ResourceManager.GetString("newopen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Photo.
        /// </summary>
        public static string newphoto {
            get {
                return ResourceManager.GetString("newphoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Product.
        /// </summary>
        public static string newproduct {
            get {
                return ResourceManager.GetString("newproduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newsletter.
        /// </summary>
        public static string newsletter {
            get {
                return ResourceManager.GetString("newsletter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Vendor.
        /// </summary>
        public static string newvendor {
            get {
                return ResourceManager.GetString("newvendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor.
        /// </summary>
        public static string onhold {
            get {
                return ResourceManager.GetString("onhold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or Login With.
        /// </summary>
        public static string orloginwith {
            get {
                return ResourceManager.GetString("orloginwith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OUR EXPORT.
        /// </summary>
        public static string ourexport {
            get {
                return ResourceManager.GetString("ourexport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our export activities are characterized with very good quality and nicely shaped packing.
        ///We are always shipping our goods exactly according to the specification
        ///agreed-upon with our clients , and are also careful to have them reached to our clients as scheduled on time..
        /// </summary>
        public static string ourexportparagraph {
            get {
                return ResourceManager.GetString("ourexportparagraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OUR IMPORT.
        /// </summary>
        public static string ourimport {
            get {
                return ResourceManager.GetString("ourimport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Import  activity include different field in addition to food stuffs 
        ///We are a leading and one of biggest importers of yarn.
        ///This division is concerned with satisfying the needs of local market with all kinds of yarn .
        ///We import from India , Malaysia , China , Thailand and other countries ..
        /// </summary>
        public static string ourimportparagraph {
            get {
                return ResourceManager.GetString("ourimportparagraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arab Traders Group Team.
        /// </summary>
        public static string ourmanagers {
            get {
                return ResourceManager.GetString("ourmanagers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string phone {
            get {
                return ResourceManager.GetString("phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo Caption Arabic.
        /// </summary>
        public static string PhotoCaptionArModel {
            get {
                return ResourceManager.GetString("PhotoCaptionArModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo Caption English.
        /// </summary>
        public static string PhotoCaptionEnModel {
            get {
                return ResourceManager.GetString("PhotoCaptionEnModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo DateTime.
        /// </summary>
        public static string PhotoDateTimeModel {
            get {
                return ResourceManager.GetString("PhotoDateTimeModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo Error.
        /// </summary>
        public static string PhotoErrorModel {
            get {
                return ResourceManager.GetString("PhotoErrorModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo Gallary.
        /// </summary>
        public static string photogallery {
            get {
                return ResourceManager.GetString("photogallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo Id.
        /// </summary>
        public static string PhotoIdModel {
            get {
                return ResourceManager.GetString("PhotoIdModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo Path.
        /// </summary>
        public static string PhotoPathModel {
            get {
                return ResourceManager.GetString("PhotoPathModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo Publisher.
        /// </summary>
        public static string PhotoPublisherModel {
            get {
                return ResourceManager.GetString("PhotoPublisherModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Your Email.
        /// </summary>
        public static string placholderemail {
            get {
                return ResourceManager.GetString("placholderemail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string product {
            get {
                return ResourceManager.GetString("product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products Album.
        /// </summary>
        public static string productalbum {
            get {
                return ResourceManager.GetString("productalbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product DateTime.
        /// </summary>
        public static string ProductDateTimeModel {
            get {
                return ResourceManager.GetString("ProductDateTimeModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string productdelete {
            get {
                return ResourceManager.GetString("productdelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Description Arabic.
        /// </summary>
        public static string ProductDescriptionArModel {
            get {
                return ResourceManager.GetString("ProductDescriptionArModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Description English.
        /// </summary>
        public static string ProductDescriptionEnModel {
            get {
                return ResourceManager.GetString("ProductDescriptionEnModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string productdetails {
            get {
                return ResourceManager.GetString("productdetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string productedit {
            get {
                return ResourceManager.GetString("productedit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Error.
        /// </summary>
        public static string ProductErrorModel {
            get {
                return ResourceManager.GetString("ProductErrorModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Id.
        /// </summary>
        public static string ProductIdModel {
            get {
                return ResourceManager.GetString("ProductIdModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string productimage {
            get {
                return ResourceManager.GetString("productimage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Image.
        /// </summary>
        public static string ProductImageModel {
            get {
                return ResourceManager.GetString("ProductImageModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products Information.
        /// </summary>
        public static string productinformation {
            get {
                return ResourceManager.GetString("productinformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string productname {
            get {
                return ResourceManager.GetString("productname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name Arabic.
        /// </summary>
        public static string ProductNameArModel {
            get {
                return ResourceManager.GetString("ProductNameArModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name English.
        /// </summary>
        public static string ProductNameEnModel {
            get {
                return ResourceManager.GetString("ProductNameEnModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        public static string productowner {
            get {
                return ResourceManager.GetString("productowner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher.
        /// </summary>
        public static string ProductPublisherModel {
            get {
                return ResourceManager.GetString("ProductPublisherModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string productquantity {
            get {
                return ResourceManager.GetString("productquantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Quantity.
        /// </summary>
        public static string ProductQuantityModel {
            get {
                return ResourceManager.GetString("ProductQuantityModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string products {
            get {
                return ResourceManager.GetString("products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher.
        /// </summary>
        public static string PublisherModel {
            get {
                return ResourceManager.GetString("PublisherModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pull-right.
        /// </summary>
        public static string pull {
            get {
                return ResourceManager.GetString("pull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string RegisterConfirmpassword {
            get {
                return ResourceManager.GetString("RegisterConfirmpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string RegisterEmail {
            get {
                return ResourceManager.GetString("RegisterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string RegisterFirstName {
            get {
                return ResourceManager.GetString("RegisterFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string RegisterLastName {
            get {
                return ResourceManager.GetString("RegisterLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string RegisterPassword {
            get {
                return ResourceManager.GetString("RegisterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related Products.
        /// </summary>
        public static string relatedproducts {
            get {
                return ResourceManager.GetString("relatedproducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.......
        /// </summary>
        public static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Deatails.
        /// </summary>
        public static string seeproductdetails {
            get {
                return ResourceManager.GetString("seeproductdetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Now.
        /// </summary>
        public static string sendnow {
            get {
                return ResourceManager.GetString("sendnow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager.
        /// </summary>
        public static string shipping {
            get {
                return ResourceManager.GetString("shipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up now.
        /// </summary>
        public static string signupnow {
            get {
                return ResourceManager.GetString("signupnow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arab Traders Group.
        /// </summary>
        public static string slidercompanyname {
            get {
                return ResourceManager.GetString("slidercompanyname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High quality, continuous development at competitive prices.
        /// </summary>
        public static string sliderh2 {
            get {
                return ResourceManager.GetString("sliderh2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to we have been working in the field of exporting fruits,vegetables and legumes ..
        /// </summary>
        public static string sliderh3 {
            get {
                return ResourceManager.GetString("sliderh3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have exported to different countries in Europe such as UK , Holland.
        /// </summary>
        public static string sliderh3br {
            get {
                return ResourceManager.GetString("sliderh3br", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We  dispatch our goods to Malaysia , Singapore and others.
        /// </summary>
        public static string sliderh3slide3 {
            get {
                return ResourceManager.GetString("sliderh3slide3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stay tune for updates.
        /// </summary>
        public static string stayupdate {
            get {
                return ResourceManager.GetString("stayupdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string subject {
            get {
                return ResourceManager.GetString("subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team.
        /// </summary>
        public static string team {
            get {
                return ResourceManager.GetString("team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string teamadd {
            get {
                return ResourceManager.GetString("teamadd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string teambtnadd {
            get {
                return ResourceManager.GetString("teambtnadd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string teambtnsave {
            get {
                return ResourceManager.GetString("teambtnsave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string teamcountry {
            get {
                return ResourceManager.GetString("teamcountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string teamdelete {
            get {
                return ResourceManager.GetString("teamdelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string teamedit {
            get {
                return ResourceManager.GetString("teamedit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string teamemail {
            get {
                return ResourceManager.GetString("teamemail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  First Name.
        /// </summary>
        public static string teamfname {
            get {
                return ResourceManager.GetString("teamfname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest Teams.
        /// </summary>
        public static string teamlatest {
            get {
                return ResourceManager.GetString("teamlatest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string teamlname {
            get {
                return ResourceManager.GetString("teamlname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string teamphone {
            get {
                return ResourceManager.GetString("teamphone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -Steven D.
        /// </summary>
        public static string testimonial1author {
            get {
                return ResourceManager.GetString("testimonial1author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have never had a company so willing and as a part of there routine make sure the job was done right. The quality control that is in place is outstanding. This testimonial is from a former Contractor and Superintendent who knows quality when he sees it. Thanks Arab Traders Group from the bottom of my heart..
        /// </summary>
        public static string testimonial1paragraph {
            get {
                return ResourceManager.GetString("testimonial1paragraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CEO / Founder.
        /// </summary>
        public static string testimonial1role {
            get {
                return ResourceManager.GetString("testimonial1role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -Bill K.
        /// </summary>
        public static string testimonial2author {
            get {
                return ResourceManager.GetString("testimonial2author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arab Traders Group  is one of the best specialized companies in the field of import and export of agricultural crops. It is always keen to trust the customers and conduct the business process efficiently.
        /// </summary>
        public static string testimonial2paragraph {
            get {
                return ResourceManager.GetString("testimonial2paragraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Manager.
        /// </summary>
        public static string testimonial2role {
            get {
                return ResourceManager.GetString("testimonial2role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -Jon B.
        /// </summary>
        public static string testimonial3author {
            get {
                return ResourceManager.GetString("testimonial3author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear Amr, I have to say I am so pleased with the way Arab Traders Group  takes care of their customers. It is a true blessing to have a company that is not there just to take the money and run.
        /// I have already recommended you to several people. I trust your company to do the right thing. Have a wonderful day..
        /// </summary>
        public static string testimonial3paragraph {
            get {
                return ResourceManager.GetString("testimonial3paragraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Manager.
        /// </summary>
        public static string testimonial3role {
            get {
                return ResourceManager.GetString("testimonial3role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -Saad M.
        /// </summary>
        public static string testimonial4author {
            get {
                return ResourceManager.GetString("testimonial4author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Arab Traders Group is one of the nicest companies I have dealt with since it helped me in the shipping and payment process, and dealing with it was flexible enough from my heart. I respect this company..
        /// </summary>
        public static string testimonial4paragraph {
            get {
                return ResourceManager.GetString("testimonial4paragraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financial Manager.
        /// </summary>
        public static string testimonial4role {
            get {
                return ResourceManager.GetString("testimonial4role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faq.
        /// </summary>
        public static string ufaq {
            get {
                return ResourceManager.GetString("ufaq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery.
        /// </summary>
        public static string ugallery {
            get {
                return ResourceManager.GetString("ugallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team.
        /// </summary>
        public static string unpaid {
            get {
                return ResourceManager.GetString("unpaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string UserEmail {
            get {
                return ResourceManager.GetString("UserEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string UserPassword {
            get {
                return ResourceManager.GetString("UserPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        public static string UserRememberme {
            get {
                return ResourceManager.GetString("UserRememberme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor.
        /// </summary>
        public static string vendor {
            get {
                return ResourceManager.GetString("vendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string vendoradd {
            get {
                return ResourceManager.GetString("vendoradd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string vendorbtnadd {
            get {
                return ResourceManager.GetString("vendorbtnadd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string vendorbtnsave {
            get {
                return ResourceManager.GetString("vendorbtnsave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string vendorcompany {
            get {
                return ResourceManager.GetString("vendorcompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string VendorCompanyEmailModel {
            get {
                return ResourceManager.GetString("VendorCompanyEmailModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company .
        /// </summary>
        public static string VendorCompanyNameModel {
            get {
                return ResourceManager.GetString("VendorCompanyNameModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string vendorcountry {
            get {
                return ResourceManager.GetString("vendorcountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string VendorCountryModel {
            get {
                return ResourceManager.GetString("VendorCountryModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DateTime.
        /// </summary>
        public static string VendorDateTimeModel {
            get {
                return ResourceManager.GetString("VendorDateTimeModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string vendordelete {
            get {
                return ResourceManager.GetString("vendordelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string vendoredit {
            get {
                return ResourceManager.GetString("vendoredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string vendoremail {
            get {
                return ResourceManager.GetString("vendoremail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor Error.
        /// </summary>
        public static string VendorErrorModel {
            get {
                return ResourceManager.GetString("VendorErrorModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor Id.
        /// </summary>
        public static string VendorIdModel {
            get {
                return ResourceManager.GetString("VendorIdModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager.
        /// </summary>
        public static string vendormanager {
            get {
                return ResourceManager.GetString("vendormanager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager Name.
        /// </summary>
        public static string VendorManagerNameModel {
            get {
                return ResourceManager.GetString("VendorManagerNameModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string vendorphone {
            get {
                return ResourceManager.GetString("vendorphone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string VendorPhoneNumberModel {
            get {
                return ResourceManager.GetString("VendorPhoneNumberModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher.
        /// </summary>
        public static string VendorPublisherModel {
            get {
                return ResourceManager.GetString("VendorPublisherModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendors.
        /// </summary>
        public static string vendors {
            get {
                return ResourceManager.GetString("vendors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View statistical.
        /// </summary>
        public static string vieworders {
            get {
                return ResourceManager.GetString("vieworders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome To  Arab Traders Group .
        /// </summary>
        public static string welcomourcompany {
            get {
                return ResourceManager.GetString("welcomourcompany", resourceCulture);
            }
        }
    }
}
