//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArabTradersGroup.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetContact
    {
        public string Contact_Id { get; set; }
        public System.DateTime Contact_DateTime { get; set; }
        public string Contact_Publisher { get; set; }
        public string Contact_Phone1 { get; set; }
        public string Contact_Phone2 { get; set; }
        public string Contact_Email { get; set; }
        public string Contact_Address { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
