//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArabTradersGroup.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetVendor
    {
        public string Vendor_Id { get; set; }
        public string Vendor_Manager { get; set; }
        public string Vendor_Company { get; set; }
        public string Vendor_Email { get; set; }
        public string Vendor_Phone { get; set; }
        public string Vendor_Country { get; set; }
        public System.DateTime Vendor_StartDateTime { get; set; }
        public string Vendor_Publisher { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
