//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArabTradersGroup.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetGallery
    {
        public string Photo_Id { get; set; }
        public string Photo_Path { get; set; }
        public System.DateTime Photo_DateTime { get; set; }
        public string Photo_Publisher { get; set; }
        public string Photo_Caption_En { get; set; }
        public string Photo_Caption_Ar { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
