//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArabTradersGroup.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetAbout
    {
        public string About_Id { get; set; }
        public string About_Publisher { get; set; }
        public System.DateTime About_DateTime { get; set; }
        public string About_Who { get; set; }
        public string About_How { get; set; }
        public string About_Us { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
