//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArabTradersGroup.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetManager
    {
        public string Manager_Id { get; set; }
        public string Manager_Fname { get; set; }
        public string Manager_Lname { get; set; }
        public string Manager_Position { get; set; }
        public string Manager_Description { get; set; }
        public string Manager_Image { get; set; }
        public string Manager_Publisher { get; set; }
        public System.DateTime Manager_DateTime { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
