//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArabTradersGroup.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetFaq
    {
        public string Faq_Id { get; set; }
        public System.DateTime Faq_DateTime { get; set; }
        public string Faq_Publisher { get; set; }
        public string Faq_Question_En { get; set; }
        public string Faq_Question_Ar { get; set; }
        public string Faq_Answer_Ar { get; set; }
        public string Faq_Answer_En { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
