//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArabTradersGroup.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetProduct
    {
        public string Product_Id { get; set; }
        public string Product_Image { get; set; }
        public System.DateTime Product_DateTime { get; set; }
        public decimal Product_Quantity { get; set; }
        public string Product_Publisher { get; set; }
        public string Product_Name_En { get; set; }
        public string Product_Name_Ar { get; set; }
        public string Product_Description_En { get; set; }
        public string Product_Description_Ar { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
